const products = [
  {
    id: 1,
    name: 'Toilet',
    price: 100,
    image: 'toilet-1.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam dolorem voluptas',
    addToCart: false,
  },
  {
    id: 2,
    name: 'Toilet',
    price: 100,
    image: 'toilet-1.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam dolorem voluptas',
    addToCart: false,
  },
  {
    id: 3,
    name: 'Toilet',
    price: 100,
    image: 'toilet-1.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam dolorem voluptas',
    addToCart: false,
  },
  {
    id: 4,
    name: 'Toilet',
    price: 100,
    image: 'toilet-1.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam dolorem voluptas',
    addToCart: false,
  },
  {
    id: 5,
    name: 'Toilet',
    price: 100,
    image: 'toilet-1.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam dolorem voluptas',
    addToCart: false,
  },
  {
    id: 6,
    name: 'Toilet',
    price: 100,
    image: 'toilet-1.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam dolorem voluptas',
    addToCart: false,
  },
  {
    id: 7,
    name: 'Toilet',
    price: 100,
    image: 'toilet-1.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam dolorem voluptas',
    addToCart: false,
  },
  {
    id: 8,
    name: 'Toilet',
    price: 100,
    image: 'toilet-1.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam dolorem voluptas',
    addToCart: false,
  },
  {
    id: 9,
    name: 'Toilet',
    price: 100,
    image: 'toilet-1.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam dolorem voluptas',
    addToCart: false,
  },
  {
    id: 10,
    name: 'Toilet',
    price: 100,
    image: 'toilet-1.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam dolorem voluptas ',
    addToCart: false,
  },
];

export default products;
